# Generated by Django 2.2.3 on 2019-08-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_catrgoryitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatrgoryItem',
            new_name='CategoryItem',
        ),
    ]
